### ISSUE TITLE
socks5 combine

### ISSUE THREAD

**Issue by sr-mehti** [HirbodBehnam/SecureForwarder#1]
Hi ,
how can i combine this system with SOCKS5 protocol?

**Comment by HirbodBehnam** [comment]
Hello
Yes you can! You can combine this with anything you want as long as you run the app on server and client.
But overally, I do not recommend using this app in production. I just wanted to see how to write a program that uses encryption to forward the traffic.
Also if you still have questions feel free to comment here and tell me to re-open with issue.
